-- Q73 rollout half — column-level read privileges for named non-owner roles.
-- GENERATED by `npm run gen:role-grants` from lib/security/roleGrants.ts + the
-- migrations themselves. Do not hand-edit: a vitest drift check compares this file to
-- the generator's output and fails on any divergence.
--
-- *** NOT APPLIED. *** Rob's go gates the rollout half. Applying this changes who can
-- read what in prod; it is committed so that go costs one `supabase db push`, not a
-- design session.
--
-- RLS is not the instrument. Row-level security filters rows; the DoD asks that a
-- booker be unable to read `quoted_amount` on a row it may otherwise see. That is a
-- column privilege, and a table-level GRANT cannot be narrowed by a column-level
-- REVOKE — hence revoke-then-grant-a-list below.

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'mle_rep_read') then
    create role mle_rep_read nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'mle_booker_read') then
    create role mle_booker_read nologin;
  end if;
end $$;

-- service_role is deliberately untouched: every server route reads through it.

-- deals — 18 columns on disk
--   withheld: equity from mle_rep_read, mle_booker_read — spin-off equity is OWNERS-ONLY (Q41)
--   withheld: value from mle_booker_read — deal size is the rep's working number, not the booker's
--   kept, deliberately: name — the deal's own label — a rep working a pipeline it cannot name is not working it. Classified PII by the bare /^name$/ pattern; a deal is not a person
revoke select on public.deals from mle_rep_read;
grant select (book_protected, created_at, estimate, id, key_dates, name, notes, org_id, owner_id, person_id, phase, referral_sourced, routing_lane, stage, updated_at, value, vertical_id) on public.deals to mle_rep_read;
revoke select on public.deals from mle_booker_read;
grant select (book_protected, created_at, estimate, id, key_dates, name, notes, org_id, owner_id, person_id, phase, referral_sourced, routing_lane, stage, updated_at, vertical_id) on public.deals to mle_booker_read;

-- invoice_ledger — 18 columns on disk
--   withheld: amount from mle_rep_read, mle_booker_read — invoiced money is the owners' ledger
--   withheld: payment_state from mle_rep_read, mle_booker_read — whether an invoice is paid is the owners' ledger — this column is the `paid` the DoD names (there is no `paid` column; it is a state value)
--   kept, deliberately: invoice_number — the ledger's primary key, an identifier and not an amount — classified money only because /invoice/ matches the name. `amount` and `payment_state` are the money on this table and both are withheld
revoke select on public.invoice_ledger from mle_rep_read;
grant select (client_legal_name, client_slug, created_at, currency, due_date, invoice_number, issue_date, owner, payment_plan_note, pdf, source_commit, source_sha256, status_text, synced_at, updated_at, withdrawn_at) on public.invoice_ledger to mle_rep_read;
revoke select on public.invoice_ledger from mle_booker_read;
grant select (client_legal_name, client_slug, created_at, currency, due_date, invoice_number, issue_date, owner, payment_plan_note, pdf, source_commit, source_sha256, status_text, synced_at, updated_at, withdrawn_at) on public.invoice_ledger to mle_booker_read;

-- orgs — 31 columns on disk
--   withheld: quoted_amount from mle_rep_read, mle_booker_read — what a customer was quoted is not a rep's or a booker's number
--   withheld: equity from mle_rep_read, mle_booker_read — spin-off equity is OWNERS-ONLY (Q41)
--   withheld: transcript_url from mle_booker_read — a booker books; other people's call recordings are not part of it
--   kept, deliberately: name — the company name is the working unit of every rep screen
--   kept, deliberately: phone — same as people.phone
--   kept, deliberately: email — same as people.email
revoke select on public.orgs from mle_rep_read;
grant select (assigned_rep, business, created_at, description, domain, email, est_time_to_payment_days, estimate, id, key_dates, legacy_slug, meeting_video_url, name, node_type, notes, phase2_estimate, phase_one, phone, referred_by_id, referred_by_org_id, relationship, role, search_tsv, signed, status, transcript_url, updated_at, vertical_id, website) on public.orgs to mle_rep_read;
revoke select on public.orgs from mle_booker_read;
grant select (assigned_rep, business, created_at, description, domain, email, est_time_to_payment_days, estimate, id, key_dates, legacy_slug, meeting_video_url, name, node_type, notes, phase2_estimate, phase_one, phone, referred_by_id, referred_by_org_id, relationship, role, search_tsv, signed, status, updated_at, vertical_id, website) on public.orgs to mle_booker_read;

-- people — 33 columns on disk
--   withheld: quoted_amount from mle_rep_read, mle_booker_read — what a customer was quoted is not a rep's or a booker's number
--   withheld: equity from mle_rep_read, mle_booker_read — spin-off equity is OWNERS-ONLY (Q41)
--   withheld: transcript_url from mle_booker_read — a booker books; other people's call recordings are not part of it
--   kept, deliberately: name — a CRM whose reps cannot see who they are calling is not a CRM
--   kept, deliberately: phone — phoning people IS the rep's and the booker's job — withholding it breaks the role instead of protecting it. Whether SOME bookers should be scoped to their own accounts is Rob's org-chart call, flagged not guessed
--   kept, deliberately: email — same as phone — outreach is the job
revoke select on public.people from mle_rep_read;
grant select (assigned_rep, business, comms_consent, created_at, description, email, entity_kind, est_time_to_payment_days, estimate, id, key_dates, legacy_slug, meeting_video_url, name, node_type, notes, org_id, phase2_estimate, phase_one, phone, referred_by_id, referred_by_org_id, relationship, role, search_tsv, signed, status, transcript_url, updated_at, vertical_id, website) on public.people to mle_rep_read;
revoke select on public.people from mle_booker_read;
grant select (assigned_rep, business, comms_consent, created_at, description, email, entity_kind, est_time_to_payment_days, estimate, id, key_dates, legacy_slug, meeting_video_url, name, node_type, notes, org_id, phase2_estimate, phase_one, phone, referred_by_id, referred_by_org_id, relationship, role, search_tsv, signed, status, updated_at, vertical_id, website) on public.people to mle_booker_read;

-- phase2_returns — 13 columns on disk
--   withheld: labor_cost_per_hour from mle_booker_read — a customer's cost basis is not a booker's
--   withheld: revenue_since_phase2_start from mle_booker_read — a customer's revenue is not a booker's
--   kept, deliberately: revenue_basis — not an amount — it names WHICH basis a figure came from ('invoiced' vs 'collected'), so it is classified money by name only
revoke select on public.phase2_returns from mle_rep_read;
grant select (created_at, customer_id, id, labor_cost_per_hour, labor_hours_saved, measured_at, measured_by, note, revenue_basis, revenue_since_phase2_start, source, superseded_at, updated_at) on public.phase2_returns to mle_rep_read;
revoke select on public.phase2_returns from mle_booker_read;
grant select (created_at, customer_id, id, labor_hours_saved, measured_at, measured_by, note, revenue_basis, source, superseded_at, updated_at) on public.phase2_returns to mle_booker_read;

-- signature_requests — 20 columns on disk
--   withheld: signer_name from mle_rep_read, mle_booker_read — who personally signed is the same evidence as the email/IP beside it — a rep needs to know a doc came back, which `signer_type` gives, not who held the pen
--   withheld: signer_email from mle_rep_read, mle_booker_read — the e-sign audit trail is evidence, not CRM data
--   withheld: signer_ip from mle_rep_read, mle_booker_read — the e-sign audit trail is evidence, not CRM data
--   withheld: signer_user_agent from mle_rep_read, mle_booker_read — the e-sign audit trail is evidence, not CRM data
--   kept, deliberately: signer_type — not identity — it is the role that signed ('customer' / 'countersigner'), and a rep tracking whether a doc came back needs it
revoke select on public.signature_requests from mle_rep_read;
grant select (channel, consent_at, created_at, document_id, expires_at, id, presend_answers, sent_to, sha256_at_sign, signed_at, signer_type, status, token_hash, updated_at, viewed_at, voided_at) on public.signature_requests to mle_rep_read;
revoke select on public.signature_requests from mle_booker_read;
grant select (channel, consent_at, created_at, document_id, expires_at, id, presend_answers, sent_to, sha256_at_sign, signed_at, signer_type, status, token_hash, updated_at, viewed_at, voided_at) on public.signature_requests to mle_booker_read;

-- Verify by reading, not by trusting. Each row is a column a role may select;
-- a withheld column must be absent from this result.
--   select grantee, table_name, column_name from information_schema.column_privileges
--   where grantee in ('mle_rep_read', 'mle_booker_read') and privilege_type = 'SELECT'
--   order by grantee, table_name, column_name;
